/* Command Center — Cloudflare Pages advanced-mode Worker (_worker.js). KV-backed session. */
const SCOPES=["openid","email","https://www.googleapis.com/auth/calendar.readonly","https://www.googleapis.com/auth/gmail.readonly"].join(" ");
const json=(o,s=200,ex={})=>new Response(JSON.stringify(o),{status:s,headers:{"content-type":"application/json; charset=utf-8",...ex}});
const redirect=(location,headers={})=>new Response(null,{status:302,headers:{location,...headers}});
function parseCookies(req){const h=req.headers.get("cookie")||"";return Object.fromEntries(h.split(/;\s*/).filter(Boolean).map(c=>{const i=c.indexOf("=");return [c.slice(0,i),decodeURIComponent(c.slice(i+1))];}));}
const allowed=env=>(env.ALLOWED_EMAILS||"").split(",").map(s=>s.trim().toLowerCase()).filter(Boolean);
const rid=()=>crypto.randomUUID().replace(/-/g,"");
const base=req=>new URL(req.url).origin;
const cookie=(v,age)=>`sid=${v}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${age}`;
async function getSession(req,env){const sid=parseCookies(req).sid;if(!sid)return null;const raw=await env.KV.get("sess:"+sid);if(!raw)return null;const s=JSON.parse(raw);s.__sid=sid;return s;}
async function saveSession(env,sid,s){const c={...s};delete c.__sid;await env.KV.put("sess:"+sid,JSON.stringify(c),{expirationTtl:60*60*24*30});}
async function freshToken(env,session){if(session.access_token&&Date.now()<(session.expiry||0)-60000)return session.access_token;if(!session.refresh_token)return null;const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,grant_type:"refresh_token",refresh_token:session.refresh_token})});if(!r.ok)return null;const t=await r.json();session.access_token=t.access_token;session.expiry=Date.now()+(t.expires_in||3600)*1000;await saveSession(env,session.__sid,session);return session.access_token;}
const gfetch=(url,token)=>fetch(url,{headers:{authorization:"Bearer "+token}});
async function authLogin(req,env){const state=rid();await env.KV.put("state:"+state,"1",{expirationTtl:600});const u=new URL("https://accounts.google.com/o/oauth2/v2/auth");u.searchParams.set("client_id",env.GOOGLE_CLIENT_ID);u.searchParams.set("redirect_uri",base(req)+"/auth/callback");u.searchParams.set("response_type","code");u.searchParams.set("scope",SCOPES);u.searchParams.set("access_type","offline");u.searchParams.set("include_granted_scopes","true");u.searchParams.set("prompt","consent");u.searchParams.set("state",state);return redirect(u.toString());}
async function authCallback(req,env){const url=new URL(req.url);const code=url.searchParams.get("code"),state=url.searchParams.get("state");if(!code||!state||!(await env.KV.get("state:"+state)))return new Response("Invalid auth state",{status:400});await env.KV.delete("state:"+state);const tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:base(req)+"/auth/callback",grant_type:"authorization_code"})});if(!tr.ok)return new Response("Token exchange failed",{status:400});const t=await tr.json();const ui=await gfetch("https://www.googleapis.com/oauth2/v2/userinfo",t.access_token).then(r=>r.json());const email=(ui.email||"").toLowerCase();const list=allowed(env);if(list.length&&!list.includes(email))return new Response("Access denied for "+email,{status:403});const sid=rid();await saveSession(env,sid,{email,name:ui.name||email,picture:ui.picture||"",access_token:t.access_token,refresh_token:t.refresh_token||"",expiry:Date.now()+(t.expires_in||3600)*1000});return redirect(base(req)+"/",{"set-cookie":cookie(sid,60*60*24*30)});}
async function authLogout(req,env){const s=await getSession(req,env);if(s)await env.KV.delete("sess:"+s.__sid);return redirect(base(req)+"/",{"set-cookie":cookie("",0)});}
async function getConfig(env){try{const raw=await env.KV.get("config:dashboard");return raw?JSON.parse(raw):{};}catch(e){return {};}}
async function apiCalendar(env,token){const cfg=await getConfig(env);const now=new Date(),end=new Date(Date.now()+(cfg.calDays||14)*864e5);const u=new URL("https://www.googleapis.com/calendar/v3/calendars/primary/events");u.searchParams.set("timeMin",now.toISOString());u.searchParams.set("timeMax",end.toISOString());u.searchParams.set("singleEvents","true");u.searchParams.set("orderBy","startTime");u.searchParams.set("maxResults","25");const d=await gfetch(u.toString(),token).then(r=>r.json());return json({events:(d.items||[]).map(e=>({summary:e.summary||"(no title)",location:e.location||"",eventType:e.eventType||"default",start:e.start||{},end:e.end||{},status:e.status}))});}
async function apiGmail(env,token){const list=await gfetch("https://gmail.googleapis.com/gmail/v1/users/me/messages?q=in%3Ainbox&maxResults=12",token).then(r=>r.json());const ids=(list.messages||[]).map(m=>m.id);const msgs=await Promise.all(ids.map(id=>gfetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/"+id+"?format=metadata&metadataHeaders=From&metadataHeaders=Subject&metadataHeaders=Date",token).then(r=>r.json())));return json({messages:msgs.map(m=>{const hs=((m.payload&&m.payload.headers)||[]).reduce((a,h)=>{a[h.name.toLowerCase()]=h.value;return a;},{});return {sender:hs.from||"",subject:hs.subject||"(no subject)",date:hs.date?new Date(hs.date).toISOString():null,snippet:m.snippet||"",labelIds:m.labelIds||[]};})});}
async function apiMarkets(env){const symbols=(env.STOCK_SYMBOLS||"GSPC,DJI,IXIC,BTC/USD,ETH/USD").split(",").map(s=>s.trim());const names={GSPC:"S&P 500",DJI:"Dow Jones",IXIC:"Nasdaq","BTC/USD":"Bitcoin","ETH/USD":"Ethereum"};const u=new URL("https://api.twelvedata.com/quote");u.searchParams.set("symbol",symbols.join(","));u.searchParams.set("apikey",env.STOCK_API_KEY||"");const d=await fetch(u.toString()).then(r=>r.json());return json({markets:symbols.map(sym=>{const q=symbols.length===1?d:(d[sym]||{});const price=parseFloat(q.close),change=parseFloat(q.change),pct=parseFloat(q.percent_change);return {symbol:sym,name:names[sym]||sym,price:isNaN(price)?null:price,change:isNaN(change)?null:change,changePercent:isNaN(pct)?null:pct};})});}
async function apiData(req,env,email,kind){const key="data:"+email+":"+kind;if(req.method==="GET"){const raw=await env.KV.get(key);return json({items:raw?JSON.parse(raw):null});}if(req.method==="PUT"){const body=await req.json();await env.KV.put(key,JSON.stringify(body.items||[]));return json({ok:true});}return json({error:"method not allowed"},405);}
export default {async fetch(request,env){const p=new URL(request.url).pathname;try{
if(p==="/auth/login")return authLogin(request,env);
if(p==="/auth/callback")return authCallback(request,env);
if(p==="/auth/logout")return authLogout(request,env);
if(p.startsWith("/api/")){const session=await getSession(request,env);if(!session)return json({error:"unauthorized"},401);
if(p==="/api/markets")return apiMarkets(env);
if(p==="/api/me")return json({email:session.email,name:session.name,picture:session.picture});
if(p==="/api/todos")return apiData(request,env,session.email,"todos");
if(p==="/api/projects")return apiData(request,env,session.email,"projects");
if(p==="/api/research"){if(request.method==="PUT"){const b2=await request.json();await env.KV.put("research:latest",JSON.stringify(b2));return json({ok:true});}const raw=await env.KV.get("research:latest");return json(raw?JSON.parse(raw):{updated:null,sections:[]});}
if(p==="/api/config"){if(request.method==="PUT"){const b3=await request.json();await env.KV.put("config:dashboard",JSON.stringify(b3));return json({ok:true});}const raw=await env.KV.get("config:dashboard");return json(raw?JSON.parse(raw):{calDays:14,accent:"#3b66f5",title:"Command Center",hidePanels:[]});}
const token=await freshToken(env,session);if(!token)return json({error:"token_expired"},401);
if(p==="/api/calendar")return apiCalendar(env,token);
if(p==="/api/gmail")return apiGmail(env,token);
return json({error:"not found"},404);}
return env.ASSETS.fetch(request);}catch(err){return json({error:String((err&&err.message)||err)},500);}}};
